### ISSUE TITLE
detect grey

### ISSUE THREAD

**Issue by ledahulevogyre** [vasilisvg/human-colours#4]
Replace"very unsaturated" by "grey" and remove the color name.

**Comment by nifl** [comment]
Purely subjective, non-scientific feedback. On my screen (Apple Tbolt), my eyes register 
* 1-3 as grey, 
* 4-10 – almost grey, 
* 11-30 – very unsaturated, 
* 31-46 – unsaturated, 
* 47-60 – rather unsaturated, 
* 61-80 – saturated, 
* 81-90 – rather saturated, 
* 91-100 – very saturated

I've added a couple names and changed highly saturated to very saturated so that my brain can follow the same pattern. While I can detect hue in what I'm calling grey, it is perceptibly grey which seems to fit the context of the project. Perhaps ranges should be defined per hue? It would be neat to have a hue selector for this test to see if pre-defined ranges hold up or an algorithm is appropriate.

**Comment by ledahulevogyre** [comment]
Yes. I think it's good. 
The change is not available on https://vasilis.nl/shop/random/100/ yet . Is it ?
